id: P26998024
initial_creation_type: input
source_metadata:
  title: 'Asaṅga: Triśatikāyāḥ Prajñāpāramitāyāḥ Kārikāsaptatiḥ'
  language: zh
  volumes:
    7d4f686be40943329e1ae33c3c65f72e:
      title: Colophon
      base_file: Colophon.txt
      work_id: W88441A94
    3c9723e4421343559ddd0a1c2afd2e7b:
      title: Preface
      base_file: Preface.txt
      work_id: WFD4BC8C3
    4aa972ef3e874393b40ca73923c4ad39:
      title: Title
      base_file: Title.txt
      work_id: W229C49BE
    8be8bb49be284bc1ab00eb901d489239:
      title: Verses 1-20
      base_file: Verses 1-20.txt
      work_id: W58A84BAC
    262a64a2bed1444b81b6447e96b550fc:
      title: Verses 21-40
      base_file: Verses 21-40.txt
      work_id: W6045313D
    ad0231a618b84044b0b827f238aea1ee:
      title: Verses 41-60
      base_file: Verses 41-60.txt
      work_id: W49198214
    e7f8518aaea14299b914365e33b6647a:
      title: Verses 61-77
      base_file: Verses 61-77.txt
      work_id: W85C2ADB7
  chapter_to_tile: {}
created_at: '2022-03-01T23:04:15.311562'
last_modified_at: '2022-03-01T23:04:15.311568'
